name: katalog
description: Oya Perde - Perde Kataloğu


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  cached_network_image: ^2.5.0
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.10
  lottie: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Capriola
      fonts:
        - asset: assets/fonts/capriola/Capriola-Regular.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/barlow/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/barlow/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/barlow/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/barlow/BarlowCondensed-Light.ttf
          weight: 300
